"""empty message

Revision ID: 4dec2cce4cd1
Revises: 28a97a5ebd9f
Create Date: 2024-07-25 02:57:13.700287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dec2cce4cd1'
down_revision = '28a97a5ebd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code', schema=None) as batch_op:
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
